name: Promote to Stage (cherry-pick)
on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  guard:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.chk.outputs.should_run }}
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - id: chk
        run: |
          if [ "${{ github.actor }}" = "repo-bot" ]; then
            echo "should_run=false" >> $GITHUB_OUTPUT; exit 0; fi
          msg="$(git log -1 --pretty=%B)"
          if echo "$msg" | grep -qE '\[promo [sp]->[ps]:'; then
            echo "Promo commit; skipping."
            echo "should_run=false" >> $GITHUB_OUTPUT; exit 0; fi
          echo "should_run=true" >> $GITHUB_OUTPUT

  promote:
    if: ${{ needs.guard.outputs.should_run == 'true' }}
    needs: guard
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Add peer remote (Repo A)
        env:
          PAT: ${{ secrets.REPO_PEER_PAT }}
          PEER_REPO: ${{ secrets.PEER_REPO }}   # e.g. ORG/repo-a
        run: |
          git remote add peer "https://${PAT}@github.com/${PEER_REPO}.git"
          git fetch peer --prune

      - name: Create promotion branch in Repo A and cherry-pick
        env:
          SHA: ${{ github.sha }}
        run: |
          BR="promo/${SHA:0:12}-p-to-s"
          git checkout -b "$BR" peer/main
          git fetch origin $SHA
          if ! git cherry-pick -x $SHA; then
            git cherry-pick --abort || true
            git checkout -b "$BR" peer/main
            git commit --allow-empty -m "Prod promotion placeholder for $SHA [promo p->s:${SHA}]"
          else
            git commit --amend -m "$(git log -1 --pretty=%B)[promo p->s:${SHA}]"
          fi
          git push peer "$BR"

      - name: Open PR in Repo A
        env:
          GH_TOKEN: ${{ secrets.REPO_PEER_PAT }}
          PEER_REPO: ${{ secrets.PEER_REPO }}
          SHA: ${{ github.sha }}
        run: |
          gh pr create \
            --repo "$PEER_REPO" \
            --head "promo/${SHA:0:12}-p-to-s" \
            --base "main" \
            --title "Prod→Stage promotion: ${SHA:0:12}" \
            --body "Automated promotion of ${SHA}. Contains trailer [promo p->s:${SHA}]." \
            --label "auto-promo,p->s"
